src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table("posts")
 * @ORM\Entity(repositoryClass="App\Repository\PostsRepository")
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     */
    private $author_id;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $create_date;

    public function __construct()
    {
        $this->create_date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;
        return $this;
    }

    public function getAuthorId(): ?int
    {
        return $this->author_id;
    }

    public function setAuthorId(int $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }
}

src/Controller/PostsController.php
<?php

namespace App\Controller;

use App\Entity\Subscription;
use App\Entity\User;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use App\Entity\Post;

class PostsController extends AbstractController
{
    /**
     * @Route("posts", name="posts_list")
     */
    public function index(LoggerInterface $logger)
    {
        $user_id = $this->getUser()->getId();

        $s_repo = $this->getDoctrine()->getManager()->getRepository(Subscription::class);
        $subscribed_ids = $s_repo->getSubscriptions($user_id);
        $subscribed_ids[] = $user_id;

        $subscriptions = $this->getDoctrine()->getManager()->getRepository(User::class)->findBy([
            'id' => $subscribed_ids
        ]);
        $_subscriptions = [];
        foreach ($subscriptions as $subscription) {
            $_subscriptions[$subscription->getId()] = $subscription;
        }
        unset($subscriptions);

        $repository = $this->getDoctrine()->getRepository(Post::class);
        $posts = $repository->findBy(
            ['author_id' => $subscribed_ids],
            ['create_date' => 'DESC']
        );

        return $this->render('posts/index.html.twig', [
            'controller_name' => 'PostsController',
            'posts' => $posts,
            'subscriptions' => $_subscriptions
        ]);
    }

    /**
     * @Route("posts/{id}", name="posts_single", requirements={"id"="\d+"})
     */
    public function show(Post $post)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->render('posts/single.html.twig', [
            'post' => $post
        ]);
    }

    /**
     * @Route("posts/{id}/delete", name="posts_delete", requirements={"id"="\d+"})
     */
    public function delete($id)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $entityManager = $this->getDoctrine()->getManager();
        $post = $entityManager->getRepository(Post::class)->find($id);

        if (!$post) {
            throw $this->createNotFoundException(
                'Нет записи для данного id ('.$id.')'
            );
        }

        if ($this->getUser()->getId() != $post->getAuthorId()) {
            throw $this->createAccessDeniedException(
                'Нет прав на удаление данной записи'
            );
        }

        $entityManager->remove($post);
        $entityManager->flush();

        return $this->redirectToRoute('posts_list');
    }

    /**
     * @Route("posts/new", name="posts_new")
     */
    public function new(Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $post = new Post();

        $form = $this->createFormBuilder($post)
            ->add('content', TextareaType::class, ['label' => 'Текст поста'])
            ->add('save', SubmitType::class, ['label' => 'Опубликовать'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post = $form->getData();
            $post->setAuthorId($this->getUser()->getId());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('posts_list');
        }

        return $this->render('posts/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/posts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Лента | {{ parent() }} {% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/posts.css') }}">

    {{ parent() }}
{% endblock %}

{% block body %}

<div class="container">
    <h1>Лента</h1>

    <br/>

    <div class="posts_list">
        {% if posts is empty %}
            <b>
                В вашей ленте пока пусто
                <a href="{{ path('users_list') }}">Подпишитесь</a> на кого-нибудь
                или <a href="{{ path('posts_new') }}">создайте</a> собственный пост
            </b>
        {% else %}
            <ul>
                {% for post in posts %}
                    {{ include('posts/list-item.html.twig', {
                        'post': post,
                        'author': subscriptions[post.authorId]
                    }) }}
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/posts/list-item.html.twig
<li class="posts_list-item">
    <div class="post_header">
        <span class="post_author">{{ author.email }}</span>
        <span class="post_date">
            {{ post.createDate|date("H:i", 'Europe/Moscow') }}
        </span>
    </div>

    <div class="post_content">
        {{ post.content }}
    </div>

    {% if post.authorId == app.user.id %}
        <div class="post_controls">
            <a class="post_delete" href="{{ path('posts_delete', {'id': post.id}) }}">Удалить</a>
        </div>
    {% endif %}

    {#<div class="post_footer">#}
        {#<span>ID: {{ post.id }}</span>#}
        {#<span>Date: {{ post.createDate|date("H:i d.m.Y", 'Europe/Moscow') }}</span>#}
    {#</div>#}
</li>

templates/posts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} Новый пост | {{ parent() }} {% endblock %}

{% block body %}
    <div class="container">
        <h1>Новый пост</h1>

        <br/>

        {{ form(form) }}
    </div>
{% endblock %}